name: LeetCode Sync

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at 12:00 AM UTC (5:30 AM IST)
  workflow_dispatch:      # Allows you to run it manually

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: LeetCode Sync
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
